[package]
name = "myth"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
# alloy
alloy-primitives = "1.0.9"

# myth
myth_constants = { path = "crates/constants" }
myth_types = { path = "crates/types" }

# ssz
r_ssz = "0.1.2"
