name: dprint-check

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  dprint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh

      - name: Run dprint check
        run: ~/.dprint/bin/dprint check