name: Lint & Clippy

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true

      - name: Run rustfmt (nightly check)
        run: cargo +nightly fmt -- --check

      - name: Run Clippy (deny warnings)
        run: cargo +nightly clippy --all-targets --all-features -- -D warnings
