name: cargo-sort

on: [push, pull_request]

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-sort
        run: cargo install cargo-sort

      - name: Check Cargo.toml sorting
        run: cargo sort --check --workspace